In [3]:
import pandas as pd
import preprocesar_set.datasets.avisos as avisos
import preprocesar_set.datasets.vistas as vistas

df = pd.read_csv('/home/luciano/orga-datos/test_final_100k.csv')

In [6]:
FEATURES = ('nombre_area', 'nombre_zona', 'tipo_de_trabajo', 'denominacion_empresa')

In [5]:
df.head()

   id  idaviso idpostulante
0   0   739260       6M9ZQR
1   1   739260       6v1xdL
2   2   739260       ezRKm9
3   3   758580       1Q35ej
4   4   758580       EAN4J6

In [14]:
df_tmp = pd.merge(df, avisos.df[list(FEATURES)], left_on='idaviso', right_index=True, how='left')

In [17]:
vistas_data = pd.merge(vistas.df, avisos.df[list(FEATURES)], left_on='idaviso', right_index=True, how='inner')

In [32]:
gb = vistas_data.groupby('idpostulante')['nombre_area'].value_counts()

In [30]:
df_tmp['cant_vistas_area'] = df_tmp['idpostulante'] + '-' + df_tmp['nombre_area']

In [33]:
def get_cant(x):
    postu, *area = x.split('-')
    clave = (postu, '-'.join(area))
    if clave in gb.index:
        return gb[clave]
    return 0
df_tmp['cant_vistas_area'] = df_tmp['cant_vistas_area'].map(get_cant)

In [37]:
df_tmp[df_tmp['cant_vistas_area'] > 1]

,id,idaviso,idpostulante,nombre_area,nombre_zona,tipo_de_trabajo,denominacion_empresa,cant_vistas_area
144,144,1672250,ZWKNBP,Ventas,Buenos Aires (fuera de GBA),Full-time,DUTY FREE SHOP,2
286,286,1785430,YoD8AD,Tecnologia / Sistemas,Capital Federal,Full-time,Baufest,2
799,799,1002181678,8J2GLR,Ventas,Gran Buenos Aires,Full-time,Wurth Argentina S.A,2
846,846,1002471470,bOVXDjY,Administración,Capital Federal,Full-time,GASTAB SOCIEDAD ANONIMA,8
982,982,1110092955,ak4V1MJ,Producción,GBA Oeste,Full-time,RANDSTAD,4
1303,1303,1110539976,JBmzQNb,Ventas,Gran Buenos Aires,Full-time,Tours Automotores SA,4
1947,1947,1111168893,eAV8Qp,Producción,Gran Buenos Aires,Full-time,SUPER -BOL,3
2872,2872,1111310458,KBeWObp,Call Center,Capital Federal,Full-time,Indicom S.A.,5
2964,2964,1111319479,EA8okJ,Ventas,Gran Buenos Aires,Part-time,EAYA Consulting,16
2990,2990,1111323240,8Vx3Qx,Administración,Gran Buenos Aires,Full-time,Radio Sapienza S.A,2
3438,3438,1111378669,YAvkwr,Ventas,Capital Federal,Part-time,Wenance,3
3492,3492,1111391460,6pejEl,Ventas,Gran Buenos Aires,Full-time,Wurth Argentina S.A,5
3533,3533,1111394973,NVmDOl,Comercial,Gran Buenos Aires,Full-time,Navent,3
3554,3554,1111397032,akjoPj0,Recepcionista,Capital Federal,Full-time,RE/MAX TITANIUM,2
3699,3699,1111412548,NB4Alz,Producción,Gran Buenos Aires,Full-time,Laboratorios Dermosoluxion S.R.L,7
5160,5160,1111522174,Z1mQZP,Comercial,Gran Buenos Aires,Full-time,BBVA Francés,3
5240,5240,1111528771,10N1YR,Producción,Gran Buenos Aires,Full-time,Grupo Gestión,3
6633,6633,1111660594,eQ6KM9,Ventas,Gran Buenos Aires,Full-time,Bazar-Bazar,4
6742,6742,1111662336,NparNx,Atención al Cliente,Gran Buenos Aires,Temporario,Consultores de Empresas SRL,4
7049,7049,1111682722,NqKmEx,Ventas,Gran Buenos Aires,Part-time,Farmacity,14
7176,7176,1111692644,1GM8zL,Call Center,Gran Buenos Aires,Part-time,silvia b. elias,4
7251,7251,1111697841,EXe902,Ventas,Gran Buenos Aires,Full-time,CREDIPAZ,3
7614,7614,1111724219,8MaQjP3,Tecnologia / Sistemas,Gran Buenos Aires,Full-time,Sofrecom,9
7945,7945,1111752504,1WzMvL,Ventas,Gran Buenos Aires,Full-time,Via Uno,7
8273,8273,1111769486,5mld6mw,Ventas,Gran Buenos Aires,Full-time,Assistem,3
8282,8282,1111769486,vVj8EAx,Ventas,Gran Buenos Aires,Full-time,Assistem,5
8591,8591,1111786150,5dodjG,Ventas,Gran Buenos Aires,Full-time,Garbarino,3
9033,9033,1111808018,EeD428,Ventas,Gran Buenos Aires,Full-time,BAYTON,3
9751,9751,1111865826,61Q1JR,Administración,Gran Buenos Aires,Full-time,LAVORIS,3
10091,10091,1111893342,aE56vJ,Administración,Gran Buenos Aires,Full-time,Suple,2
...,...,...,...,...,...,...,...,...
88796,88796,1112467018,5mPxvap,Comercial,Gran Buenos Aires,Part-time,Farmacity,2
88797,88797,1112467018,mz5X0B1,Comercial,Gran Buenos Aires,Part-time,Farmacity,2
88872,88872,1112467020,59ZX6v,Comercial,Gran Buenos Aires,Full-time,Farmacity,2
88922,88922,1112467020,5mPxvap,Comercial,Gran Buenos Aires,Full-time,Farmacity,2
88954,88954,1112467020,zvawaPk,Comercial,Gran Buenos Aires,Full-time,Farmacity,2
89039,89039,1112467020,4rPNeDA,Comercial,Gran Buenos Aires,Full-time,Farmacity,2
89289,89289,1112467020,0zdZV4Y,Comercial,Gran Buenos Aires,Full-time,Farmacity,5
89653,89653,1112467034,5mPxvap,Comercial,Gran Buenos Aires,Part-time,Farmacity,2
89659,89659,1112467034,Z1v4mZ,Comercial,Gran Buenos Aires,Part-time,Farmacity,7
89709,89709,1112467034,4rPNeDA,Comercial,Gran Buenos Aires,Part-time,Farmacity,2
89735,89735,1112467034,zvawaPk,Comercial,Gran Buenos Aires,Part-time,Farmacity,2
89749,89749,1112467034,96zjbjP,Comercial,Gran Buenos Aires,Part-time,Farmacity,2
89913,89913,1112467104,NPZd8J,Recursos Humanos,Gran Buenos Aires,Full-time,Lighthouse Smart,4
89920,89920,1112467104,Zabmk8,Recursos Humanos,Gran Buenos Aires,Full-time,Lighthouse Smart,2
89921,89921,1112467104,EPLdBo,Recursos Humanos,Gran Buenos Aires,Full-time,Lighthouse Smart,2
89948,89948,1112467173,8MaQjP3,Ventas,Gran Buenos Aires,Full-time,Lighthouse Smart,7
89950,89950,1112467173,96XjBeP,Ventas,Gran Buenos Aires,Full-time,Lighthouse Smart,2
89970,89970,1112467175,EzZA0O8,Call Center,Gran Buenos Aires,Part-time,Activo Contact Center,2
90062,90062,1112467175,lDLXjDG,Call Center,Gran Buenos Aires,Part-time,Activo Contact Center,2
90075,90075,1112467175,mz5X0B1,Call Center,Gran Buenos Aires,Part-time,Activo Contact Center,2
90235,90235,1112467226,8MaQjP3,Administración,Gran Buenos Aires,Full-time,Adecco -Región GBA SUR,5
90246,90246,1112467226,edqVBW,Administración,Gran Buenos Aires,Full-time,Adecco -Región GBA SUR,4
90273,90273,1112467277,LNw6Qwr,Ventas,Gran Buenos Aires,Part-time,EAYA Consulting,4
90281,90281,1112467277,Z1v4mZ,Ventas,Gran Buenos Aires,Part-time,EAYA Consulting,12
90297,90297,1112467315,jkV55b6,Legal,Gran Buenos Aires,Full-time,Garantizar,3
90308,90308,1112467339,8MaQjP3,Administración,Capital Federal,Full-time,Excelencia Laboral S.A.,5
91531,91531,1112471849,Nr8RmM,Administración,Gran Buenos Aires,Full-time,Adecco -Región GBA SUR,2
93744,93744,1112480772,E0pED6,Ventas,Gran Buenos Aires,Full-time,Holcim Argentina,5
96390,96390,1112493962,aDwAR0,Administración,Gran Buenos Aires,Full-time,ANTONELA L RUSSO,3
99364,99364,1112511857,8RvMJz,Ventas,Gran Buenos Aires,Full-time,Pepsico de Argentina SRL,3

In [38]:
vistas_data = pd.merge(vistas.df, df[['idpostulante']], on='idpostulante', how='inner')

In [39]:
vistas_data.head()

      idaviso idpostulante
0  1112357825       5pJE9X
1  1112359096       5pJE9X
2  1112308963       5pJE9X
3  1112359096       5pJE9X
4  1112335751       5pJE9X

In [40]:
vistas_data

          idaviso idpostulante
0      1112357825       5pJE9X
1      1112359096       5pJE9X
2      1112308963       5pJE9X
3      1112359096       5pJE9X
4      1112335751       5pJE9X
5      1112290061       5pJE9X
6      1112343243       5pJE9X
7      1112297071      qe246AR
8      1112352091      qe246AR
9      1112356904      qe246AR
10     1112314115      qe246AR
11     1112355412      qe246AR
12     1112320003      qe246AR
13     1112348205      qe246AR
14     1112356904      qe246AR
15     1112320003      qe246AR
16     1112358460      qe246AR
17     1112290063      qe246AR
18     1112320003      qe246AR
19     1112339723      qe246AR
20     1112340000      qe246AR
21     1112295720      qe246AR
22     1112302181      qe246AR
23     1112340000      qe246AR
24     1112280587       al9vZZ
25     1112280587       al9vZZ
26     1112202358       N0AJmD
27     1112202358       N0AJmD
28     1112202358       N0AJmD
29     1111912708       N0AJmD
...           ...          ...
35033  1112348491        12lBB
35034  1112359230       885LMR
35035  1112359377        ZPWlE
35036  1112200601       YLVeZJ
35037  1112200601       YLVeZJ
35038  1112359616       eG52e8
35039  1112359616       eG52e8
35040  1112359653       60V1kR
35041  1112360304      0zPEmD8
35042  1112360304      0zPEmD8
35043  1112359880       YRMpwr
35044  1112360304       5Nbpeq
35045  1112360580       1oYzQz
35046  1112347635       ZGQoEE
35047  1112352365       exEjX9
35048  1112348218       exEjX9
35049  1112357553       Z61j5V
35050  1112020797       aOGjwJ
35051  1112360571       a8Ap8Z
35052  1112352275       Y15D9J
35053  1112359390       5pBOWX
35054  1112360580      dYJALRq
35055  1112360580      dYJALRq
35056  1112360580      dYJALRq
35057  1112360580      dYJALRq
35058  1112360580      dYJALRq
35059  1112360580      dYJALRq
35060  1112360580      dYJALRq
35061  1112360580      dYJALRq
35062  1112360580      dYJALRq

[35063 rows x 2 columns]

In [41]:
import preprocesar_set.datasets.postulaciones as postulaciones

Cargando postulaciones...OK

In [54]:
id_postulante = 'ZPWlE'
df = pd.DataFrame(vistas.df.loc[vistas.df['idpostulante'] == id_postulante])[['idaviso']]
df['factor'] = 1
df = df.append(pd.DataFrame(postulaciones.df.loc[postulaciones.df['idpostulante'] == id_postulante])[['idaviso']])
df['factor'] = df['factor'].fillna(2)

/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

In [57]:
df['factor'].value_counts()

2.0    127
1.0      1
Name: factor, dtype: int64

In [58]:
pd.DataFrame(vistas.df.loc[vistas.df['idpostulante'] == id_postulante])[['idaviso']]

          idaviso
99470  1112359377

In [64]:
gb = vistas.df.groupby('idpostulante')

In [71]:
gb.get_group('a' +id_postulante)['idaviso'].map(lambda x: print(x))

KeyError: 'aZPWlE'

In [77]:
'a' + id_postulante in gb.groups

False

In [78]:
dft = pd.read_csv('/home/luciano/orga-datos/test_final_100k-preprocesado.csv')

In [79]:
dft.head()

,id,idaviso,idpostulante,sexo_postulante,edad_postulante,educacion_postulante,cantidad_vistas,cantidad_postulaciones,cant_vistas_nombre_area,cant_vistas_nombre_zona,cant_vistas_tipo_de_trabajo,cant_vistas_denominacion_empresa,cant_postulaciones_nombre_area,cant_postulaciones_nombre_zona,cant_postulaciones_tipo_de_trabajo,cant_postulaciones_denominacion_empresa,desc_score
0,0,739260,6M9ZQR,-1,42,0,0,0,0,0,0,0,0,0,0,0,0
1,1,739260,6v1xdL,1,31,0,0,0,0,0,0,0,0,0,0,0,0
2,2,739260,ezRKm9,-1,36,0,0,0,0,0,0,0,0,0,0,0,0
3,3,758580,1Q35ej,1,69,0,0,0,0,0,0,0,0,0,0,0,0
4,4,758580,EAN4J6,-1,32,0,0,0,0,0,0,0,0,0,0,0,0

In [81]:
dft[dft['desc_score'] > 1]

,id,idaviso,idpostulante,sexo_postulante,edad_postulante,educacion_postulante,cantidad_vistas,cantidad_postulaciones,cant_vistas_nombre_area,cant_vistas_nombre_zona,cant_vistas_tipo_de_trabajo,cant_vistas_denominacion_empresa,cant_postulaciones_nombre_area,cant_postulaciones_nombre_zona,cant_postulaciones_tipo_de_trabajo,cant_postulaciones_denominacion_empresa,desc_score
20,20,1141070,edaNB4,-1,34,0,17,0,0,0,0,0,0,0,0,0,28
45,45,1263850,NWAKoB,-1,41,0,44,0,0,0,0,0,0,0,0,0,556
52,52,1294380,NmBAkx,-1,40,0,1,0,0,0,1,0,0,0,0,0,12
71,71,1491320,Np1Zr4,-1,28,0,1,0,0,0,1,0,0,0,0,0,4
99,99,1551320,ZR4jk5,-1,32,0,2,0,0,2,2,0,0,0,0,0,60
100,100,1551320,Ew2ww9,-1,46,0,4,0,0,0,4,0,0,0,0,0,32
110,110,1573840,aeVoX9,-1,33,0,12,0,1,1,9,0,0,0,0,0,56
144,144,1672250,ZWKNBP,-1,31,0,2,0,2,0,0,0,0,0,0,0,12
161,161,1720280,EkEb06,1,33,0,4,0,0,0,4,0,0,0,0,0,52
205,205,1755800,E2QG8z,-1,35,0,1,0,0,0,1,0,0,0,0,0,6
208,208,1757480,YVXr4Y,-1,47,0,12,0,0,2,11,0,0,0,0,0,73
248,248,1768960,N0b0pB,-1,41,0,2,0,0,0,0,0,0,0,0,0,20
270,270,1772140,YZAmor,1,37,0,9,0,0,4,9,0,0,0,0,0,126
271,271,1772770,eAVN0B,-1,37,0,2,0,0,0,0,0,0,0,0,0,6
286,286,1785430,YoD8AD,1,36,0,5,0,2,2,5,0,0,0,0,0,148
306,306,1788430,aRmdJ0,-1,38,0,5,0,0,1,5,0,0,0,0,0,39
315,315,1788910,5DaXEq,-1,31,0,9,0,0,2,16,0,0,0,0,0,94
330,330,1789020,6VM59L,-1,38,0,3,0,0,0,3,0,0,0,0,0,36
353,353,1791860,5DaZJN,1,31,0,9,0,0,0,9,0,0,0,0,0,135
369,369,1799480,6Q3DLO,-1,34,0,5,0,0,0,5,0,0,0,0,0,100
458,458,1803360,8VvOv3,-1,32,0,1,0,0,0,1,0,0,0,0,0,5
465,465,1803800,Ezxjv6,-1,52,0,0,4,0,0,0,0,0,0,2,0,27
479,479,1803890,ZDbA5b,-1,39,0,2,60,0,0,2,0,0,7,48,0,207
550,550,1805750,ekwEoW,-1,36,0,1,0,0,0,0,0,0,0,0,0,3
554,554,1805780,YRbOqr,1,57,0,9,0,0,1,9,0,0,0,0,0,54
573,573,2580550,6V4LKj,-1,34,0,3,7,0,0,0,0,0,0,0,0,32
604,604,1000132160,E2Qe4b,1,34,0,1,0,0,1,1,0,0,0,0,0,2
615,615,1000240169,8j0lL,1,37,0,4,0,0,0,4,0,0,0,0,0,39
799,799,1002181678,8J2GLR,1,32,0,2,0,2,2,0,0,0,0,0,0,22
808,808,1002231302,5qz6Xw,-1,30,0,2,0,0,2,2,0,0,0,0,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99365,99365,1112511857,EweqXz,-1,36,0,1,0,0,0,1,0,0,0,0,0,6
99375,99375,1112511870,YqrBYq,-1,33,0,14,0,0,14,13,0,0,0,0,0,125
99480,99480,1112512178,8R3lqD,-1,29,0,2,0,0,0,2,0,0,0,0,0,14
99521,99521,1112512353,Eb3wjz,-1,36,0,1,0,0,1,1,0,0,0,0,0,6
99524,99524,1112512392,5Nlp5Z,1,37,0,2,0,0,2,2,0,0,0,0,0,10
99544,99544,1112512593,ZvRWGz,1,53,0,2,0,0,2,2,0,0,0,0,0,42
99550,99550,1112512597,ZR2d2Z,-1,34,0,1,0,0,1,0,0,0,0,0,0,2
99589,99589,1112512777,1R3PKj,-1,43,0,3,0,0,0,3,0,0,0,0,0,3
99619,99619,1112513024,1R3ReR,1,40,0,38,0,0,36,35,4,0,0,0,0,237
99633,99633,1112513099,eZMwoE,-1,35,0,3,0,0,3,3,0,0,0,0,0,26
99648,99648,1112513147,EwPxmN,-1,35,0,6,0,0,6,6,0,0,0,0,0,75
99657,99657,1112513170,Yv8VRZ,1,38,0,2,0,0,2,2,0,0,0,0,0,16
99680,99680,1112513334,1xoDQL,1,53,0,3,0,0,3,3,0,0,0,0,0,3
99681,99681,1112513334,Z0povR,1,41,0,11,0,0,11,11,0,0,0,0,0,67
99692,99692,1112513367,ZRDV68,1,32,0,2,0,0,2,2,0,0,0,0,0,35
99703,99703,1112513463,50D0PX,1,34,0,2,0,0,2,0,0,0,0,0,0,8
99775,99775,1112513728,ND9jNx,1,35,0,1,0,0,1,1,0,0,0,0,0,9
99780,99780,1112513740,NRmMGV,-1,35,0,10,0,0,10,4,0,0,0,0,0,39
99841,99841,1112513927,8ROj4D,-1,28,0,2,0,0,4,4,0,0,0,0,0,24
99844,99844,1112513960,ar8OeE,1,39,0,3,0,0,0,0,0,0,0,0,0,8
99850,99850,1112514020,NDoBvl,-1,34,0,4,0,0,2,0,0,0,0,0,0,83
99875,99875,1112514148,eZV3M9,1,52,0,5,0,0,5,5,0,0,0,0,0,125
99877,99877,1112514169,1R5mJO,-1,41,0,1,0,0,1,1,0,0,0,0,0,5
99900,99900,1112514408,Ebopj6,1,47,0,1,0,0,1,1,0,0,0,0,0,2
99938,99938,1112514975,ND46Px,-1,25,0,5,0,0,4,5,0,0,0,0,0,59
99958,99958,1112515019,arE39E,1,67,0,2,0,0,2,2,0,0,0,0,0,34
99959,99959,1112515019,aZJLK9,1,34,0,3,0,0,3,3,0,0,0,0,0,35
99961,99961,1112515021,509b4q,1,41,0,8,0,0,8,8,0,0,0,0,0,78
99964,99964,1112515030,12W3PO,-1,34,0,1,0,0,1,0,0,0,0,0,0,9
99991,99991,1112515105,ZREdK1,-1,32,0,4,0,0,4,4,0,0,0,0,0,42